import { ComponentInfo } from '@/models';

export const vbtn: ComponentInfo = {
  id: 'vuetify/VBtn',
  libraryId: 'vuetify',
  name: 'VBtn',
  slots: [
    {
      id: 'default',
      name: 'Children',
      type: 'text-property',
      defaultValue: 'Click Me!',
    },
  ],
  dynamicDefinitions: {
    data: [],
    functions: [],
    properties: [
      {
        id: 'absolute',
        name: 'Absolute',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'active-class',
        name: 'Active Class',
        type: 'text-property',
        defaultValue: 'v-btn--active',
      },
      {
        id: 'append',
        name: 'Append',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'block',
        name: 'Block',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'color',
        name: 'Color',
        type: 'text-property',
        defaultValue: 'primary',
      },
      {
        id: 'dark',
        name: 'Dark',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'depressed',
        name: 'Depressed',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'disabled',
        name: 'Disabled',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'exact',
        name: 'Exact',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'exact-active-class',
        name: 'Exact Active Class',
        type: 'text-property',
        defaultValue: undefined,
      },
      {
        id: 'fab',
        name: 'Fab',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'fixed',
        name: 'Fixed',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'flat',
        name: 'Flat',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'href',
        name: 'Href',
        type: 'text-property',
        defaultValue: '',
      },
      {
        id: 'icon',
        name: 'Icon',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'input-value',
        name: 'Input Value',
        type: 'text-property',
        defaultValue: '',
      },
      {
        id: 'large',
        name: 'Large',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'left',
        name: 'Left',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'light',
        name: 'Light',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'loading',
        name: 'Loading',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'nuxt',
        name: 'Nuxt',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'outline',
        name: 'Outline',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'replace',
        name: 'Replace',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'right',
        name: 'Right',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'ripple',
        name: 'Ripple',
        type: 'boolean-property',
        defaultValue: undefined,
      },
      {
        id: 'round',
        name: 'Round',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'small',
        name: 'Small',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'tag',
        name: 'Tag',
        type: 'text-property',
        defaultValue: 'button',
      },
      {
        id: 'target',
        name: 'Target',
        type: 'text-property',
        defaultValue: undefined,
      },
      {
        id: 'to',
        name: 'To',
        type: 'text-property',
        defaultValue: undefined,
      },
      {
        id: 'top',
        name: 'Top',
        type: 'boolean-property',
        defaultValue: 'false',
      },
      {
        id: 'type',
        name: 'Type',
        type: 'text-property',
        defaultValue: 'button',
      },
      {
        id: 'value',
        name: 'Value',
        type: 'text-property',
        defaultValue: '',
      },
    ],
  },
};
